spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev 
  application:
    name: microservicecloud-config-mpj-dev
---
spring:
  profiles: test 
  application:
    name: microservicecloud-config-mpj-test
#请保存为utf-8格式
